idf_component_register(
    SRCS
        "battery_pct.cpp"
        "main.cpp"
        "onboard_led.cpp"
        "sensors.cpp"
        "zigbee.cpp"
        "../components/SHT4x/SHT4x.cpp"
        "../components/LTR30x/LTR308.cpp"
    INCLUDE_DIRS 
        "."
        "../components/SHT4x"
        "../components/LTR30x"
)
